### ISSUE TITLE
Receiving messages 

### ISSUE THREAD

**Issue by barsbaatar2** [sendbird/Sendbird-Flutter#6]
Doesn't the app use push or socket or etc. for receiving new massages?

I tested from another device to send message, and my device didn't receive new message directly.
Just by refreshing channel list, the app was getting new messages. 

How does the app handle receiving messages?
When will this improve?

**Comment by intoxicated** [comment]
No push notification has not been setup for this example

**Comment by intoxicated** [comment]
Thanks for the report. I just pushed new commit to fix this issue.

**Comment by barsbaatar2** [comment]
So to resolve this issue, I need to pull this project, update. Right?
I updated project, and there was some updates in 3 files. But the issue didn't resolve...
How can I fix in my project?

**Comment by intoxicated** [comment]
@barsbaatar2 are you still not getting message on channel when you send a message from a device to another device?

**Comment by intoxicated** [comment]
Close the issue, feel free to reopen if you still have question regard this matter.
